name: AI Infra Deploy

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: Infrastructure request
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      USER_PROMPT: ${{ github.event.inputs.prompt }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install google-generativeai

      - run: python scripts/generate_tf.py

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: terraform

      - run: terraform validate
        working-directory: terraform

      - run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
