name: AI Kiro Infra Pipeline

on:
  workflow_dispatch:
    inputs:
      request:
        description: Enter request
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Input
        run: |
          echo "User Request: ${{ github.event.inputs.request }}"
